using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.PlayerLoop;

/// <summary>
/// 节拍线的视觉层脚本
/// </summary>
public class BeatLinesController : BaseNote
{
    void Awake()
    {
        _transform = gameObject.GetComponent<Transform>();
    }
    void Update()
    {
        UpdateRenderer(_songInformation.SongCurrentTime, _BPMGroup.CurrentNoteSpeed);
        //CheckMiss(_songInformation.SongCurrentTime, _BPMGroup.InitializeOffset);
    }
    public void Init(float targetTime, SongInformationContainer container, BPMGroup timing)
    {
        TargetTime = targetTime;
        _songInformation = container;
        _BPMGroup = timing;
    }
}
