using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class BuildingOptionPanelController : MonoBehaviour
{
    public Button DragButton;
    public Button NoteButton;
    public Button FlickButton;
    public Button DataFlowButton;
    public Button LandMineButton;
    public Button ZipButton;
    private Transform _transfrom;
    void Awake()
    {
        _transfrom = gameObject.GetComponent<Transform>();
        //Drag = _transfrom.Find("Drag").GetComponent<Button>();
    }

    // Update is called once per frame
    void Update()
    {

    }
}
